### ISSUE TITLE
messages和models下的bean都缺少默认构造方法，toString时被Gson调用会异常

### ISSUE THREAD

**Issue by tianshaojie** [rongcloud/server-sdk-java#20]
java.lang.RuntimeException: No-args constructor for class xxx.utils.rongcloud.models.TokenResult does not exist. Register an InstanceCreator with Gson for this type to fix this problem.
	at com.google.gson.MappedObjectConstructor.constructWithNoArgConstructor(MappedObjectConstructor.java:64)
	at com.google.gson.MappedObjectConstructor.construct(MappedObjectConstructor.java:53)
	at com.google.gson.JsonObjectDeserializationVisitor.constructTarget(JsonObjectDeserializationVisitor.java:40)
	at com.google.gson.JsonDeserializationVisitor.getTarget(JsonDeserializationVisitor.java:56)
	at com.google.gson.ObjectNavigator.accept(ObjectNavigator.java:109)
	at com.google.gson.JsonDeserializationContextDefault.fromJsonObject(JsonDeserializationContextDefault.java:73)
	at com.google.gson.JsonDeserializationContextDefault.deserialize(JsonDeserializationContextDefault.java:51)
	at com.google.gson.Gson.fromJson(Gson.java:495)
	at com.google.gson.Gson.fromJson(Gson.java:444)
	at com.google.gson.Gson.fromJson(Gson.java:396)
	at xxx.utils.rongcloud.util.GsonUtil.fromJson(GsonUtil.java:18)
	at xxx.utils.rongcloud.methods.User.getToken(User.java:58)

**Comment by chaoohua** [comment]
您好3.0版本 此问题已经解决，在2.0中有对应返回值参数的构造函数。我们推荐使用最新版本
